### ISSUE TITLE
Investigate using a11y-disabled-modifier

### ISSUE THREAD

**Issue by meirish** [hashicorp/structure#101]
This was in the most recent issue of ember times - the issue is that when a button is disabled, a screen reader can't focus it so it can't be read. This modifier https://github.com/chriskrycho/a11y-disabled-modifier uses aria attributes to implement an accessible pattern for disabling buttons.

We should look at adding this to `Pds::Button` when `@disabled` is true.

**Comment by MelSumner** [comment]
@meirish when an interactive icon is disabled, it is _supposed_ to be ignored by assistive technology (AT).

**Comment by didoo** [comment]
Outdated. Closing now.
