### ISSUE TITLE
Typography fallback issue in Firefox

### ISSUE THREAD

**Issue by evankerrigan** [hashicorp/structure#76]
### Background
Our [primary font stack](https://github.com/hashicorp/structure/blob/main/packages/pds-ember/app/styles/pds/tokens/_font.scss#L16) makes use of the user’s standard system typeface by way of the `system-ui` value for the `font-family` property.

### The problem
On Apple devices in particular, using `system-ui` should generally render using Apple’s [“San Francisco” typeface](https://developer.apple.com/fonts/). Leading browsers such as Chrome, Edge, Opera, and Safari [all offer full support for this value](https://caniuse.com/?search=system-ui); however, Firefox does not, despite having [a bug open against this](https://bugzilla.mozilla.org/show_bug.cgi?id=1226042) for nearly 6 years. This results in Firefox users on Apple devices seeing the UI using another fallback typeface. While our UI should still be more than usable, this isn’t ideal.

### A potential solution
While Firefox still doesn’t support the `system-ui` value for `font-family`, there is a workaround to enable the use of the “San Francisco” typeface on Apple devices. I propose that we add `-apple-system,` in the fallback list for `$family--sans` immediately [before this line](https://github.com/hashicorp/structure/blob/main/packages/pds-ember/app/styles/pds/tokens/_font.scss#L18), in between `system-ui` and `"Segoe UI"`.

Doing so will render Firefox on Mac as intended and will not have an impact on other browsers. If Firefox does ultimately decide to fully support `system-ui` as a value, it will ignore the `-apple-system` value.

**Comment by didoo** [comment]
Outdated. Closing now.
