### ISSUE TITLE
Dropdown styles clobber button styles variations

### ISSUE THREAD

**Issue by gregone** [hashicorp/structure#89]
I was trying to build an action dropdown using `<Pds::Dropdown>` and `<Pds::Button>` and noticed that the Dropdown styles clobber the selected button variation (`warning`) by resetting the `--pds-color` variable. 

<img width="215" alt="Screen Shot 2021-05-21 at 20 34 16" src="https://user-images.githubusercontent.com/1416421/119183521-7cefe000-ba74-11eb-8bb9-bf7fae1f663b.png">
(expected: `Delete` should be red)
<img width="784" alt="Screen Shot 2021-05-21 at 20 34 49" src="https://user-images.githubusercontent.com/1416421/119183535-811bfd80-ba74-11eb-83f3-6aac3047ce45.png">

**Comment by didoo** [comment]
Outdated. Closing now.
