### ISSUE TITLE
Dropdown Styles aren't applying as expected to Pds::ExternalLinks

### ISSUE THREAD

**Issue by emoncuso** [hashicorp/structure#92]
When an `PDS::ExternalLink` is within a `PDS::Dropdown` dialog, the styles for the link are not consistent with what you would expect them to be. 

<img width="1092" alt="Screen Shot 2021-06-18 at 8 13 51 AM" src="https://user-images.githubusercontent.com/46458931/122584186-e8df4d00-d00e-11eb-9b23-ff63af0f0b1e.png">

**NOTE** this does NOT happen with internal links from Ember's `LinkTo` component. There seems to be a rule somewhere applying only to external links (this selector: `.pds-dropdownDialog :any-link:not(.pds-button):not(.pds--external)`)

**Comment by Dhaulagiri** [comment]
Seems possible this is related to https://github.com/hashicorp/structure/issues/89

**Comment by didoo** [comment]
Outdated. Closing now.
