### ISSUE TITLE
Table-like layouts

### ISSUE THREAD

**Issue by gregone** [hashicorp/structure#93]
Our apps use a lot of list layouts (see examples below). 

Structure currently only provides the `<Pds::Toolbar/>` component, but it would be nice to have additional standardized components for the elements that compose such layouts: 
- table-like list
- pagination
- action dropdowns for list items

The scope and the coupling of those elements may be a case that requires a separate addon, but I'm not entirely sure.

## Examples

Waypoint
<img width="1624" alt="Screen Shot 2021-06-22 at 13 49 45" src="https://user-images.githubusercontent.com/1416421/122920065-42be7a80-d361-11eb-95a9-ab9bab86c79c.png">

Consul
<img width="1264" alt="Screen Shot 2021-06-22 at 13 49 17" src="https://user-images.githubusercontent.com/1416421/122920092-49e58880-d361-11eb-9d24-d11163e2607b.png">

Nomad
<img width="782" alt="Screen Shot 2021-06-22 at 13 48 43" src="https://user-images.githubusercontent.com/1416421/122920107-4eaa3c80-d361-11eb-995c-5a0c80481af6.png">

**Comment by didoo** [comment]
Outdated. Closing now.
